---
name: Build

on:
  pull_request:
  push:
    branches:
      - main
  # schedule:
  #   - cron: "10 1 * * 0"

jobs:
  prep:
    name: Prepare envionment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: c-py/action-dotenv-to-setenv@v2
        with:
          env-file: .env

  # Test the image builds and works correctly.
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: prep
    steps:
      - uses: actions/checkout@v3

      - name: Test building image.
        run: docker build -t docker-ansible -f Dockerfile.${BUILD_LATEST}.

      - name: Run the built image.
        run: docker run --name test-container -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro docker-ansible

      - name: Verify Ansible is accessible in the built image.
        run: docker exec --tty test-container env TERM=xterm ansible --version

  # If on main branch, build and release image.
  # release:
  #   name: Release
  #   runs-on: ubuntu-latest
  #   needs: test
  #   if: github.ref == 'refs/heads/main'

    # steps:
    #   - uses: actions/checkout@v3
    #   - uses: docker/setup-qemu-action@v2
    #   - uses: docker/setup-buildx-action@v2

    #   - name: Login to DockerHub
    #     uses: docker/login-action@v2
    #     with:
    #       username: ${{ secrets.DOCKERHUB_USERNAME }}
    #       password: ${{ secrets.DOCKERHUB_TOKEN }}

    #   - name: Build and push image.
    #     uses: docker/build-push-action@v3
    #     with:
    #       context: ./
    #       file: Dockerfile
    #       platforms: linux/amd64,linux/arm64
    #       push: true
    #       tags: ${{ github.repository }}:latest
